# Generated by Django 2.2.5 on 2019-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img',
            field=models.FileField(upload_to='img-brend/'),
        ),
    ]
