# Generated by Django 2.2.5 on 2019-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brend', '0002_auto_20190919_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='img',
            field=models.FileField(upload_to='static/img-brend/'),
        ),
    ]
